---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: |-
      # Set up required version of Node and NPM
      export NVM_DIR=/home/pipeline/nvm
      export NODE_VERSION=7.0.0
      export NVM_VERSION=0.33.0

      npm config delete prefix \
        && curl https://raw.githubusercontent.com/creationix/nvm/v${NVM_VERSION}/install.sh | sh \
        && . $NVM_DIR/nvm.sh \
        && nvm install $NODE_VERSION \
        && nvm alias default $NODE_VERSION \
        && nvm use default \
        && node -v \
        && npm -v

      # Install & build
      npm install
      npm run build

      tar -czf node_modules.tar.gz node_modules
      rm -rf node_modules
- name: Test
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Linting and Unit Tests
    type: tester
    script: |-
      #!/bin/bash

      #test command here

    enable_tests: true
    test_file_pattern: tests/reports/unit-tests.xml
- name: Test Environment
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy: Test
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_TEST_APP_NAME}
    script: |
      #!/bin/bash
      cf push "${CF_APP}"
- name: Production Environment
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
    enabled: false
  jobs:
  - name: Deploy Prod
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      cf push "${CF_APP}"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
