---
stages:
- name: Build
  inputs:
- url: ${SAMPLE_REPO}
  type: git
  branch: master
  dir_name: null
triggers:
- type: commit
jobs:
- name: Build
 type: builder
 artifact_dir: ''
 build_type: npm
 script: |-
   export PATH=/opt/IBM/node-v4.2/bin:$PATH

   # Install & build
   npm install
   npm run build

   tar -czf node_modules.tar.gz node_modules
   rm -rf node_modules
- name: Test
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Test
    type: tester
    script: |-
      #!/bin/bash

      tar -xzf node_modules.tar.gz

      #Test command here
    enable_tests: true
    test_file_pattern: tests/TEST-*.xml
- name: 'Deploy: Test Environment'
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: 'Deploy: Test'
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_TEST_APP_NAME}
    script: |
      #!/bin/bash
      cf push "${CF_APP}"
- name: 'Deploy: Production Environment'
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  jobs:
  - name: 'Deploy: Prod'
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      cf push "${CF_APP}"

      # View logs
      # cf logs "${CF_APP}" --recent
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
